import numpy as np
import ROOT as r
import os
import sys


#dyData = ['/store/user/mcarrigan/fakeTracks/converted_madgraph_fullSelection_4PlusLayer_v7p1/', '/store/user/mcarrigan/fakeTracks/converted_aMC_fullSelection_4PlusLayer_v7p1/']
dyData = ['/store/user/mcarrigan/fakeTracks/converted_aMC_cat0p1_4PlusLayer_v7p1/']

signalData = ['/store/user/mcarrigan/fakeTracks/converted_higgsino_700_10_4PlusLayer_v7p1/', '/store/user/mcarrigan/fakeTracks/converted_higgsino_700_100_4PlusLayer_v7p1/',
              '/store/user/mcarrigan/fakeTracks/converted_higgsino_700_1000_4PlusLayer_v7p1/', '/store/user/mcarrigan/fakeTracks/converted_higgsino_700_10000_4PlusLayer_v7p1/']

#trackIso, eta, phi, nPV, dRMinJet, ecalo, pt, d0, dz, charge, nValidPixelHits, nValidHits, missingOuterHits, dEdxPixel, dEdxStrip, numMeasurementsPixel,
                          #numMeasurementsStrip, numSatMeasurementsPixel, numSatMeasurementsStrip]

out = r.TFile("plottedVariablesMC.root", "recreate")

layers = 6

h_trackIso = r.TH1F("h_trackIso", "Track Iso", 100, 0, 50) 
h_eta = r.TH1F("h_eta", "Eta", 50, -2.5, 2.5)
h_phi = r.TH1F("h_phi", "Phi", 100, -4, 4)
h_nPV = r.TH1F("h_nPV", "nPV", 125, 0, 125)
h_drMinJet = r.TH1F("h_drMinJet", "dRMinJet", 110, -1, 10)
h_ecalo = r.TH1F("h_ecalo", "Ecalo", 1000, 0, 1000)
h_pt = r.TH1F("h_pt", "PT", 1000, 0, 1000)
h_d0 = r.TH1F("h_d0", "d0", 100, -0.1, 0.1)
h_dz = r.TH1F("h_dz", "dz", 50, -1, 1)
h_charge = r.TH1F("h_charge", "Charge", 2, -1, 1)
h_pixelHits = r.TH1F("h_pixelHits", "Valid Pixel Hits", 15, 0, 15)
h_Hits = r.TH1F("h_Hits", "Valid Hits", 40, 0, 40)
h_missingOuter = r.TH1F("h_missingOuter", "Number of Missing Outer Hits", 16, 0, 16)
h_dEdxPixel = r.TH1F("h_dEdxPixel", "dEdx Pixel", 100, 0, 10)
h_dEdxStrip = r.TH1F("h_dEdxStrip", "dEdx Strip", 100, 0, 10)
h_pixelMeasurements = r.TH1F("h_pixelMeasurements", "Number of Pixel Measurements", 15, 0, 15)
h_stripMeasurements = r.TH1F("h_stripMeasurements", "Number of Strip Measurements", 30, 0, 30)
h_pixelSat = r.TH1F("h_pixelSat", "Number of Saturated Pixel Measurements", 10, 0, 10)
h_stripSat = r.TH1F("h_stripSat", "Number of Saturated Strip Meausrements", 15, 0, 15)


h_layer1 = r.TH1F("h_layer1", "Layer", 10, 0, 10)
h_charge1 = r.TH1F("h_charge1", "Charge", 200, 0, 200)
h_subDet1 = r.TH1F("h_subDet1", "SubDetector", 20, -10, 10)
h_pixelHitSize1 = r.TH1F("h_pixelHitSize1", "Pixel Hit Size", 21, -1, 20)
h_pixelHitSizeX1 = r.TH1F("h_pixelHitSizeX1", "Pixel Hit Size X", 11, -1, 10)
h_pixelHitSizeY1 = r.TH1F("h_pixelHitSizeY1", "Pixel Hit Size Y", 16, -1, 15)
h_stripSelection1 = r.TH1F("h_stripSelection1", "Strip Selection", 2, 0, 2)
h_hitPosX1 = r.TH1F("h_hitPosX1", "Hit Position X", 100, -10, 10)
h_hitPosY1 = r.TH1F("h_hitPosY1", "Hit Position Y", 200, -20, 20)

h_layer2 = r.TH1F("h_layer2", "Layer", 10, 0, 10)
h_charge2 = r.TH1F("h_charge2", "Charge", 200, 0, 200)
h_subDet2 = r.TH1F("h_subDet2", "SubDetector", 20, -10, 10)
h_pixelHitSize2 = r.TH1F("h_pixelHitSize2", "Pixel Hit Size", 21, -1, 20)
h_pixelHitSizeX2 = r.TH1F("h_pixelHitSizeX2", "Pixel Hit Size X", 11, -1, 10)
h_pixelHitSizeY2 = r.TH1F("h_pixelHitSizeY2", "Pixel Hit Size Y", 16, -1, 15)
h_stripSelection2 = r.TH1F("h_stripSelection2", "Strip Selection", 2, 0, 2)
h_hitPosX2 = r.TH1F("h_hitPosX2", "Hit Position X", 100, -10, 10)
h_hitPosY2 = r.TH1F("h_hitPosY2", "Hit Position Y", 200, -20, 20)

h_layer3 = r.TH1F("h_layer3", "Layer", 10, 0, 10)
h_charge3 = r.TH1F("h_charge3", "Charge", 200, 0, 200)
h_subDet3 = r.TH1F("h_subDet3", "SubDetector", 20, -10, 10)
h_pixelHitSize3 = r.TH1F("h_pixelHitSize3", "Pixel Hit Size", 21, -1, 20)
h_pixelHitSizeX3 = r.TH1F("h_pixelHitSizeX3", "Pixel Hit Size X", 11, -1, 10)
h_pixelHitSizeY3 = r.TH1F("h_pixelHitSizeY3", "Pixel Hit Size Y", 16, -1, 15)
h_stripSelection3 = r.TH1F("h_stripSelection3", "Strip Selection", 2, 0, 2)
h_hitPosX3 = r.TH1F("h_hitPosX3", "Hit Position X", 100, -10, 10)
h_hitPosY3 = r.TH1F("h_hitPosY3", "Hit Position Y", 200, -20, 20)

h_layer4 = r.TH1F("h_layer4", "Layer", 10, 0, 10)
h_charge4 = r.TH1F("h_charge4", "Charge", 200, 0, 200)
h_subDet4 = r.TH1F("h_subDet4", "SubDetector", 20, -10, 10)
h_pixelHitSize4 = r.TH1F("h_pixelHitSize4", "Pixel Hit Size", 21, -1, 20)
h_pixelHitSizeX4 = r.TH1F("h_pixelHitSizeX4", "Pixel Hit Size X", 11, -1, 10)
h_pixelHitSizeY4 = r.TH1F("h_pixelHitSizeY4", "Pixel Hit Size Y", 16, -1, 15)
h_stripSelection4 = r.TH1F("h_stripSelection4", "Strip Selection", 2, 0, 2)
h_hitPosX4 = r.TH1F("h_hitPosX4", "Hit Position X", 100, -10, 10)
h_hitPosY4 = r.TH1F("h_hitPosY4", "Hit Position Y", 200, -20, 20)

h_layer5 = r.TH1F("h_layer5", "Layer", 10, 0, 10)
h_charge5 = r.TH1F("h_charge5", "Charge", 200, 0, 200)
h_subDet5 = r.TH1F("h_subDet5", "SubDetector", 20, -10, 10)
h_pixelHitSize5 = r.TH1F("h_pixelHitSize5", "Pixel Hit Size", 21, -1, 20)
h_pixelHitSizeX5 = r.TH1F("h_pixelHitSizeX5", "Pixel Hit Size X", 11, -1, 10)
h_pixelHitSizeY5 = r.TH1F("h_pixelHitSizeY5", "Pixel Hit Size Y", 16, -1, 15)
h_stripSelection5 = r.TH1F("h_stripSelection5", "Strip Selection", 2, 0, 2)
h_hitPosX5 = r.TH1F("h_hitPosX5", "Hit Position X", 100, -10, 10)
h_hitPosY5 = r.TH1F("h_hitPosY5", "Hit Position Y", 200, -20, 20)

h_layer6 = r.TH1F("h_layer6", "Layer", 10, 0, 10)
h_charge6 = r.TH1F("h_charge6", "Charge", 200, 0, 200)
h_subDet6 = r.TH1F("h_subDet6", "SubDetector", 20, -10, 10)
h_pixelHitSize6 = r.TH1F("h_pixelHitSize6", "Pixel Hit Size", 21, -1, 20)
h_pixelHitSizeX6 = r.TH1F("h_pixelHitSizeX6", "Pixel Hit Size X", 11, -1, 10)
h_pixelHitSizeY6 = r.TH1F("h_pixelHitSizeY6", "Pixel Hit Size Y", 16, -1, 15)
h_stripSelection6 = r.TH1F("h_stripSelection6", "Strip Selection", 2, 0, 2)
h_hitPosX6 = r.TH1F("h_hitPosX6", "Hit Position X", 100, -10, 10)
h_hitPosY6 = r.TH1F("h_hitPosY6", "Hit Position Y", 200, -20, 20)

h_layers = [h_layer1, h_layer2, h_layer3, h_layer4, h_layer5,h_layer6]
h_charges = [h_charge1, h_charge2, h_charge3, h_charge4, h_charge5, h_charge6]
h_subDets = [h_subDet1, h_subDet2, h_subDet3, h_subDet4, h_subDet5, h_subDet6]
h_pixelHitSizes = [h_pixelHitSize1, h_pixelHitSize2, h_pixelHitSize3, h_pixelHitSize4, h_pixelHitSize5, h_pixelHitSize6]
h_pixelHitSizesX = [h_pixelHitSizeX1, h_pixelHitSizeX2, h_pixelHitSizeX3, h_pixelHitSizeX4, h_pixelHitSizeX5, h_pixelHitSizeX6]
h_pixelHitSizesY = [h_pixelHitSizeY1, h_pixelHitSizeY2, h_pixelHitSizeY3, h_pixelHitSizeY4, h_pixelHitSizeY5, h_pixelHitSizeY6]
h_stripSelections = [h_stripSelection1, h_stripSelection2, h_stripSelection3, h_stripSelection4, h_stripSelection5, h_stripSelection6]
h_hitPosXs = [h_hitPosX1, h_hitPosX2, h_hitPosX3, h_hitPosX4, h_hitPosX5, h_hitPosX6]
h_hitPosYs = [h_hitPosY1, h_hitPosY2, h_hitPosY3, h_hitPosY4, h_hitPosY5, h_hitPosY6]

def plotTogether(base_name, dataset_names, filename, outfile = 'combinedPlots_4PlusLayer.root'):

    colors = [1, 1, 2, 2, 3, 3, 4, 4, 6, 6, 7, 7, 9, 9]
    outfile = r.TFile(outfile, 'update')
    file = r.TFile.Open(filename)
    histograms = []

    for i in range(len(dataset_names)):
        h = file.Get(base_name+dataset_names[i])
        print(base_name+dataset_names[i])
        h.Sumw2()
        if(h.Integral() > 0): h.Scale(float(1)/h.Integral())
        h.SetName('h' + str(i))
        histograms.append(h)


    l1 = r.TLegend(0.7, 0.7, 0.8, 0.9)
    c1 = r.TCanvas("c1", base_name, 800, 800)
    c1.cd()
    for hist in range(len(histograms)):
        histograms[hist].SetMaximum(1)
        if hist == 0: 
            if(histograms[hist].GetEntries()>0): histograms[hist].Draw("HIST")
            histograms[hist].SetLineColor(colors[hist])
            l1.AddEntry(histograms[hist], dataset_names[hist], "l")
        else:
            if(histograms[hist].GetEntries()>0): histograms[hist].Draw("HIST SAME")
            histograms[hist].SetLineColor(colors[hist])
            if('fake' in dataset_names[hist]): histograms[hist].SetLineStyle(2)
            l1.AddEntry(histograms[hist], dataset_names[hist], "l")


    l1.Draw("SAME")
    outfile.cd()
    c1.Write(base_name)

    outfile.Close()
    file.Close()
    c1.Delete()
    del histograms



def plotDataset(datasets, track_types, track_names):

    for j in range(len(track_types)):
        for dataset in datasets:
            for filename in os.listdir(dataset):
                if 'npz' not in filename: continue
                #if int((filename.split('_')[1]).split('.')[0])>20: continue
                print("Loading file..." + dataset + filename)
                myfile = np.load(dataset+filename)
                tracks = myfile[track_types[j]]
                print("Number of tracks..." + str(len(tracks)))
                for i in range(len(tracks)):
                    h_trackIso.Fill(tracks[i,0])
                    h_eta.Fill(tracks[i,1])
                    h_phi.Fill(tracks[i,2])
                    h_nPV.Fill(tracks[i,3])
                    h_drMinJet.Fill(tracks[i,4])
                    h_ecalo.Fill(tracks[i,5])
                    h_pt.Fill(tracks[i,6])
                    h_d0.Fill(tracks[i,7])
                    h_dz.Fill(tracks[i,8])
                    h_charge.Fill(tracks[i,9])
                    h_pixelHits.Fill(tracks[i,10])
                    h_Hits.Fill(tracks[i,11])
                    h_missingOuter.Fill(tracks[i,12])
                    h_dEdxPixel.Fill(tracks[i,13])
                    h_dEdxStrip.Fill(tracks[i,14])
                    h_pixelMeasurements.Fill(tracks[i,15])
                    h_stripMeasurements.Fill(tracks[i,16])
                    h_pixelSat.Fill(tracks[i,17])
                    h_stripSat.Fill(tracks[i,18])
                    h_layers[0].Fill(tracks[i, 19])
                    h_charges[0].Fill(tracks[i,20])
                    h_subDets[0].Fill(tracks[i, 21])
                    h_pixelHitSizes[0].Fill(tracks[i,22])
                    h_pixelHitSizesX[0].Fill(tracks[i,23])
                    h_pixelHitSizesY[0].Fill(tracks[i, 24])
                    h_stripSelections[0].Fill(tracks[i,25])
                    h_hitPosXs[0].Fill(tracks[i,26])
                    h_hitPosYs[0].Fill(tracks[i,27])
                    h_layers[1].Fill(tracks[i, 28])
                    h_charges[1].Fill(tracks[i,29])
                    h_subDets[1].Fill(tracks[i, 30])
                    h_pixelHitSizes[1].Fill(tracks[i,31])
                    h_pixelHitSizesX[1].Fill(tracks[i,32])
                    h_pixelHitSizesY[1].Fill(tracks[i, 33])
                    h_stripSelections[1].Fill(tracks[i,34])
                    h_hitPosXs[1].Fill(tracks[i,35])
                    h_hitPosYs[1].Fill(tracks[i,36])
                    h_layers[2].Fill(tracks[i, 37])
                    h_charges[2].Fill(tracks[i,38])
                    h_subDets[2].Fill(tracks[i, 39])
                    h_pixelHitSizes[2].Fill(tracks[i,40])
                    h_pixelHitSizesX[2].Fill(tracks[i,41])
                    h_pixelHitSizesY[2].Fill(tracks[i, 42])
                    h_stripSelections[2].Fill(tracks[i,43])
                    h_hitPosXs[2].Fill(tracks[i,44])
                    h_hitPosYs[2].Fill(tracks[i,45])
                    h_layers[3].Fill(tracks[i, 46])
                    h_charges[3].Fill(tracks[i,47])
                    h_subDets[3].Fill(tracks[i, 48])
                    h_pixelHitSizes[3].Fill(tracks[i,49])
                    h_pixelHitSizesX[3].Fill(tracks[i,50])
                    h_pixelHitSizesY[3].Fill(tracks[i, 51])
                    h_stripSelections[3].Fill(tracks[i,52])
                    h_hitPosXs[3].Fill(tracks[i,53])
                    h_hitPosYs[3].Fill(tracks[i,54])
                    if(layers < 5): continue
                    h_layers[4].Fill(tracks[i, 55])
                    h_charges[4].Fill(tracks[i,56])
                    h_subDets[4].Fill(tracks[i, 57])
                    h_pixelHitSizes[4].Fill(tracks[i,58])
                    h_pixelHitSizesX[4].Fill(tracks[i,59])
                    h_pixelHitSizesY[4].Fill(tracks[i, 60])
                    h_stripSelections[4].Fill(tracks[i,61])
                    h_hitPosXs[4].Fill(tracks[i,62])
                    h_hitPosYs[4].Fill(tracks[i,63])
                    if(layers < 6): continue
                    h_layers[5].Fill(tracks[i, 64])
                    h_charges[5].Fill(tracks[i,65])
                    h_subDets[5].Fill(tracks[i, 66])
                    h_pixelHitSizes[5].Fill(tracks[i,67])
                    h_pixelHitSizesX[5].Fill(tracks[i,68])
                    h_pixelHitSizesY[5].Fill(tracks[i, 69])
                    h_stripSelections[5].Fill(tracks[i,70])
                    h_hitPosXs[5].Fill(tracks[i,71])
                    h_hitPosYs[5].Fill(tracks[i,72])
                myfile.close()

        # Write the histograms to root file           
        h_trackIso.Write('h_trackIso_' + track_names[j])
        h_eta.Write('h_eta_' + track_names[j])
        h_phi.Write('h_phi_' + track_names[j])
        h_nPV.Write('h_nPV_' + track_names[j])
        h_drMinJet.Write('h_drMinJet_' + track_names[j])
        h_ecalo.Write('h_ecalo_' + track_names[j])
        h_pt.Write('h_pt_' + track_names[j])
        h_d0.Write('h_d0_' + track_names[j])
        h_dz.Write('h_dz_' + track_names[j])
        h_charge.Write('h_charge_' + track_names[j])
        h_pixelHits.Write('h_pixelHits_' + track_names[j])
        h_Hits.Write('h_Hits_' + track_names[j])
        h_missingOuter.Write('h_missingOuter_' + track_names[j])
        h_dEdxPixel.Write('h_dEdxPixel_' + track_names[j])
        h_dEdxStrip.Write('h_dEdxStrip_' + track_names[j])
        h_pixelMeasurements.Write('h_pixelMeasurements_' + track_names[j])
        h_stripMeasurements.Write('h_stripMeasurements_' + track_names[j])
        h_pixelSat.Write('h_pixelSat_' + track_names[j])
        h_stripSat.Write('h_stripSat_' + track_names[j])
        h_layers[0].Write('h_layer1_' + track_names[j])
        h_charges[0].Write('h_charge1_' + track_names[j])
        h_subDets[0].Write('h_subDet1_' + track_names[j])
        h_pixelHitSizes[0].Write('h_pixelHitSize1_' + track_names[j])
        h_pixelHitSizesX[0].Write('h_pixelHitSizeX1_' + track_names[j])
        h_pixelHitSizesY[0].Write('h_pixelHitSizeY1_' + track_names[j])
        h_stripSelections[0].Write('h_stripSelection1_' + track_names[j])
        h_hitPosXs[0].Write('h_hitPosX1_' + track_names[j])
        h_hitPosYs[0].Write('h_hitPosY1_' + track_names[j])
        h_layers[1].Write('h_layer2_' + track_names[j])
        h_charges[1].Write('h_charge2_' + track_names[j])
        h_subDets[1].Write('h_subDet2_' + track_names[j])
        h_pixelHitSizes[1].Write('h_pixelHitSize2_' + track_names[j])
        h_pixelHitSizesX[1].Write('h_pixelHitSizeX2_' + track_names[j])
        h_pixelHitSizesY[1].Write('h_pixelHitSizeY2_' + track_names[j])
        h_stripSelections[1].Write('h_stripSelection2_' + track_names[j])
        h_hitPosXs[1].Write('h_hitPosX2_' + track_names[j])
        h_hitPosYs[1].Write('h_hitPosY2_' + track_names[j])
        h_layers[2].Write('h_layer3_' + track_names[j])
        h_charges[2].Write('h_charge3_' + track_names[j])
        h_subDets[2].Write('h_subDet3_' + track_names[j])
        h_pixelHitSizes[2].Write('h_pixelHitSize3_' + track_names[j])
        h_pixelHitSizesX[2].Write('h_pixelHitSizeX3_' + track_names[j])
        h_pixelHitSizesY[2].Write('h_pixelHitSizeY3_' + track_names[j])
        h_stripSelections[2].Write('h_stripSelection3_' + track_names[j])
        h_hitPosXs[2].Write('h_hitPosX3_' + track_names[j])
        h_hitPosYs[2].Write('h_hitPosY3_' + track_names[j])
        h_layers[3].Write('h_layer4_' + track_names[j])
        h_charges[3].Write('h_charge4_' + track_names[j])
        h_subDets[3].Write('h_subDet4_' + track_names[j])
        h_pixelHitSizes[3].Write('h_pixelHitSize4_' + track_names[j])
        h_pixelHitSizesX[3].Write('h_pixelHitSizeX4_' + track_names[j])
        h_pixelHitSizesY[3].Write('h_pixelHitSizeY4_' + track_names[j])
        h_stripSelections[3].Write('h_stripSelection4_' + track_names[j])
        h_hitPosXs[3].Write('h_hitPosX4_' + track_names[j])
        h_hitPosYs[3].Write('h_hitPosY4_' + track_names[j])
        if(layers < 5): continue
        h_layers[4].Write('h_layer5_' + track_names[j])
        h_charges[4].Write('h_charge5_' + track_names[j])
        h_subDets[4].Write('h_subDet5_' + track_names[j])
        h_pixelHitSizes[4].Write('h_pixelHitSize5_' + track_names[j])
        h_pixelHitSizesX[4].Write('h_pixelHitSizeX5_' + track_names[j])
        h_pixelHitSizesY[4].Write('h_pixelHitSizeY5_' + track_names[j])
        h_stripSelections[4].Write('h_stripSelection5_' + track_names[j])
        h_hitPosXs[4].Write('h_hitPosX5_' + track_names[j])
        h_hitPosYs[4].Write('h_hitPosY5_' + track_names[j])
        if(layers < 6): continue
        h_layers[5].Write('h_layer6_' + track_names[j])
        h_charges[5].Write('h_charge6_' + track_names[j])
        h_subDets[5].Write('h_subDet6_' + track_names[j])
        h_pixelHitSizes[5].Write('h_pixelHitSize6_' + track_names[j])
        h_pixelHitSizesX[5].Write('h_pixelHitSizeX6_' + track_names[j])
        h_pixelHitSizesY[5].Write('h_pixelHitSizeY6_' + track_names[j])
        h_stripSelections[5].Write('h_stripSelection6_' + track_names[j])
        h_hitPosXs[5].Write('h_hitPosX6_' + track_names[j])
        h_hitPosYs[5].Write('h_hitPosY6_' + track_names[j])

        #clear the histograms for the next set
        h_trackIso.Reset()
        h_eta.Reset()
        h_phi.Reset()
        h_nPV.Reset()
        h_drMinJet.Reset()
        h_ecalo.Reset()
        h_pt.Reset()
        h_d0.Reset()
        h_dz.Reset()
        h_charge.Reset()
        h_pixelHits.Reset()
        h_Hits.Reset()
        h_missingOuter.Reset()
        h_dEdxPixel.Reset()
        h_dEdxStrip.Reset()
        h_pixelMeasurements.Reset()
        h_stripMeasurements.Reset()
        h_pixelSat.Reset()
        h_stripSat.Reset()
        h_layers[0].Reset()
        h_charges[0].Reset()
        h_subDets[0].Reset()
        h_pixelHitSizes[0].Reset()
        h_pixelHitSizesX[0].Reset()
        h_pixelHitSizesY[0].Reset()
        h_stripSelections[0].Reset()
        h_hitPosXs[0].Reset()
        h_hitPosYs[0].Reset()
        h_layers[1].Reset()
        h_charges[1].Reset()
        h_subDets[1].Reset()
        h_pixelHitSizes[1].Reset()
        h_pixelHitSizesX[1].Reset()
        h_pixelHitSizesY[1].Reset()
        h_stripSelections[1].Reset()
        h_hitPosXs[1].Reset()
        h_hitPosYs[1].Reset()
        h_layers[2].Reset()
        h_charges[2].Reset()
        h_subDets[2].Reset()
        h_pixelHitSizes[2].Reset()
        h_pixelHitSizesX[2].Reset()
        h_pixelHitSizesY[2].Reset()
        h_stripSelections[2].Reset()
        h_hitPosXs[2].Reset()
        h_hitPosYs[2].Reset()
        h_layers[3].Reset()
        h_charges[3].Reset()
        h_subDets[3].Reset()
        h_pixelHitSizes[3].Reset()
        h_pixelHitSizesX[3].Reset()
        h_pixelHitSizesY[3].Reset()
        h_stripSelections[3].Reset()
        h_hitPosXs[3].Reset()
        h_hitPosYs[3].Reset()
        if(layers < 5): continue
        h_layers[4].Reset()
        h_charges[4].Reset()
        h_subDets[4].Reset()
        h_pixelHitSizes[4].Reset()
        h_pixelHitSizesX[4].Reset()
        h_pixelHitSizesY[4].Reset()
        h_stripSelections[4].Reset()
        h_hitPosXs[4].Reset()
        h_hitPosYs[4].Reset()
        if(layers < 6): continue
        h_layers[5].Reset()
        h_charges[5].Reset()
        h_subDets[5].Reset()
        h_pixelHitSizes[5].Reset()
        h_pixelHitSizesX[5].Reset()
        h_pixelHitSizesY[5].Reset()
        h_stripSelections[5].Reset()
        h_hitPosXs[5].Reset()
        h_hitPosYs[5].Reset()
            


track_types = ['real_infos', 'fake_infos', 'pileup_infos']
dy_track_names = ['real_DY', 'fake_DY', 'pileup_DY']
higgsino_10_names = ['real_10', 'fake_10']
higgsino_100_names = ['real_100', 'fake_100']
higgsino_1000_names = ['real_1000', 'fake_1000']
higgsino_10000_names = ['real_10000', 'fake_10000']

plotDataset(dyData, track_types, dy_track_names)
#plotDataset([signalData[0]], track_types, higgsino_10_names)
#plotDataset([signalData[1]], track_types, higgsino_100_names)
#plotDataset([signalData[2]], track_types, higgsino_1000_names)
#plotDataset([signalData[3]], track_types, higgsino_10000_names)



out.Close()


plotTogether('h_trackIso_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_eta_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_phi_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_nPV_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_drMinJet_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_ecalo_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_d0_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_dz_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_pt_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_charge_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_pixelHits_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_Hits_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_missingOuter_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_dEdxPixel_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_pixelMeasurements_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_stripMeasurements_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_pixelSat_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_stripSat_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_layer1_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_charge1_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_subDet1_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_pixelHitSize1_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_pixelHitSizeX1_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_pixelHitSizeY1_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_stripSelection1_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_hitPosX1_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_hitPosY1_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_layer2_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_charge2_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_subDet2_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_pixelHitSize2_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_pixelHitSizeX2_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_pixelHitSizeY2_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_stripSelection2_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_hitPosX2_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_hitPosY2_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_layer3_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_charge3_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_subDet3_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_pixelHitSize3_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_pixelHitSizeX3_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_pixelHitSizeY3_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_stripSelection3_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_hitPosX3_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_hitPosY3_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_layer4_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_charge4_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_subDet4_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_pixelHitSize4_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_pixelHitSizeX4_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_pixelHitSizeY4_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_stripSelection4_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_hitPosX4_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_hitPosY4_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_layer5_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_charge5_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_subDet5_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_pixelHitSize5_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_pixelHitSizeX5_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_pixelHitSizeY5_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_stripSelection5_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_hitPosX5_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_hitPosY5_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_layer6_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_charge6_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_subDet6_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_pixelHitSize6_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_pixelHitSizeX6_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_pixelHitSizeY6_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_stripSelection6_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_hitPosX6_', dy_track_names, "plottedVariablesMC.root")
plotTogether('h_hitPosY6_', dy_track_names, "plottedVariablesMC.root")


